name: user_app
description: SapuJagad: Pesan & Bersih (User App)
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  shared_models:
    path: ../shared_models
  shared_services:
    path: ../shared_services
  shared_ui:
    path: ../shared_ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/