include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/build/**"
    - "**/.dart_tool/**"
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: true
    always_declare_return_types: true
    cancel_subscriptions: true
    close_sinks: true