name: shared_models
description: Shared data models for SapuJagad apps.
version: 0.1.0
publish_to: 'none'
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  equatable: ^2.0.5
dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0