name: shared_ui
description: Shared Flutter UI components and themes for SapuJagad.
version: 0.1.0
publish_to: 'none'
environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"
dependencies:
  flutter:
    sdk: flutter
  shared_models:
    path: ../shared_models
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true