name: shared_services
description: Shared business logic and services for SapuJagad apps.
version: 0.1.0
publish_to: 'none'
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  shared_models:
    path: ../shared_models
  collection: ^1.18.0
dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0